version: "3.9"
services:
  web:
    image: ghcr.io/blixthalka/divdash-web:master
    ports:
      - "80:80"
    depends_on:
      - core
  core:
    image: ghcr.io/blixthalka/divdash-core:master
    expose:
      - "8082"
    volumes:
      - "/divdash/mnesia:/divdash/mnesia"